version: "3.5"
services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root!
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pw
      MYSQL_DATABASE: springboot24
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql

#  spring:
#    image: docker.io/library/spring-boot-24-to-25-example:0.0.1-SNAPSHOT
#    ports:
#      - 8080:8080
#    environment:
#      MYSQL_HOST: mysql

#volumes:
#  db_data:
